#include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

int main(int argc, char const *argv[])
{
    int sum = 2, term1 = 1, term2 = 2, nextTerm = 3;
    while (nextTerm <= 4000000)
    {
        if (nextTerm % 2 == 0)
        {
            sum += nextTerm;
        }
        nextTerm = term1 + term2;
        term1 = term2;
        term2 = nextTerm;
    }
    printf("%d", sum);
    return 0;
}
